apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec: 
  selector: 
    app: movies
  ports:
    - port : 80
      targetPort: 5000 #porta do container
      nodePort: 30000 #porta do node
  type: LoadBalancer